In [5]:
import numpy as np
import pandas as pd

In [6]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [8]:
df = pd.DataFrame(data, columns = columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [11]:
df.head(n= 3)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [12]:
da = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    # ...
]

In [14]:
cf = pd.DataFrame(da)
cf

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [16]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [22]:
df[['Year', 'Model', 'MSRP', 'Make']]

   Year     Model   MSRP     Make
0  1991    Stanza   2000   Nissan
1  2017    Sonata  27150  Hyundai
2  2010     Elise  54990    Lotus
3  2017    Acadia  34450      GMC
4  2017  Frontier  32340   Nissan

In [27]:
df['id'] = [1,2,3,4,5]

In [28]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [29]:
del df['id']

In [30]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [31]:
df.index = [1,2,3,4,5]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
5,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [32]:
df.loc[2]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 2, dtype: object

In [52]:
df = df.reset_index(drop = True)
df

,level_0,index,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,0,0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,1,1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,2,2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,3,3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,4,4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [58]:
df[
    (df['Year'] >= 2017) & (df['Make'] == 'Nissan')
]

,level_0,index,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,4,4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [70]:
df['Make'].describe()

count          5
unique         4
top       Nissan
freq           2
Name: Make, dtype: object

In [74]:
df['Transmission Type'].describe()

count          5
unique         2
top       MANUAL
freq           3
Name: Transmission Type, dtype: object

In [73]:
df['MSRP'].describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [77]:
df.describe().round(1)

       level_0  index    Year  Engine HP  Engine Cylinders     MSRP
count      5.0    5.0     5.0        4.0               5.0      5.0
mean       2.0    2.0  2010.4      202.8               4.4  30186.0
std        1.6    1.6    11.3       51.3               0.9  18985.0
min        0.0    0.0  1991.0      138.0               4.0   2000.0
25%        1.0    1.0  2010.0      180.0               4.0  27150.0
50%        2.0    2.0  2017.0      206.0               4.0  32340.0
75%        3.0    3.0  2017.0      228.8               4.0  34450.0
max        4.0    4.0  2017.0      261.0               6.0  54990.0

In [78]:
df.nunique()

level_0              5
index                5
Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        5
MSRP                 5
dtype: int64

In [79]:
df.isnull().sum()

level_0              0
index                0
Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [82]:
lf =df.to_dict(orient = 'records')
lf

[{'level_0': 0,
  'index': 0,
  'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'level_0': 1,
  'index': 1,
  'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150},
 {'level_0': 2,
  'index': 2,
  'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'level_0': 3,
  'index': 3,
  'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450},
 {'level_0': 4,
  'index': 4,
  'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340}]

In [81]:
df.groupby('Transmission Type').MSRP.min()

Transmission Type
AUTOMATIC    27150
MANUAL        2000
Name: MSRP, dtype: int64

In [86]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [84]:
pd.DataFrame(lf)

,level_0,index,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,0,0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,1,1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,2,2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,3,3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,4,4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340